@hostname=localhost
@port=7155
@baseurl={{hostname}}:{{port}}

# Get all wallets 
GET http://{{baseurl}}/api/wallets


###
# Get wallet by id
GET http://{{baseurl}}/api/wallets/1

###
# Post wallet 
PUT http://{{baseurl}}/api/UpsertWallet
Content-Type: application/json

{
    "name": "My Wallet",
    "description": "My Wallet Description",
    "balance": 1000,
    "currency": "EUR",
    "type": 1
}
